-- Waitlist signups. One row per customer or business submission.
--
-- form-specific fields (service interests, certifications, social links, …)
-- live in `details` rather than as columns, since the two forms collect
-- different fields and both change over time as the forms are edited.
CREATE TABLE IF NOT EXISTS signups (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  form_type TEXT NOT NULL CHECK (form_type IN ('customer', 'business')),
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  postcode TEXT,
  details JSONB NOT NULL,

  -- Idempotency key generated by the browser. Lets a retried submission
  -- (e.g. after a dropped response) be recognised instead of creating a
  -- duplicate row and sending a second confirmation email.
  submission_id TEXT UNIQUE,

  confirmation_email_sent_at TIMESTAMPTZ,
  confirmation_email_error TEXT,

  -- Whether the copy forwarded to the Google Sheet (via Apps Script) landed.
  sheet_synced_at TIMESTAMPTZ,
  sheet_sync_error TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_signups_email ON signups (email);
CREATE INDEX IF NOT EXISTS idx_signups_form_type ON signups (form_type);
CREATE INDEX IF NOT EXISTS idx_signups_created_at ON signups (created_at);
